name: khoa_luan_tot_ngiep_gia_su_nguoi_hoc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  http: ^1.5.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  url_launcher: ^6.1.10
  bloc: ^9.1.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  file_picker: ^8.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/img/logo.png
    - assets/img/onboarding.png
